[terminal.shell]
program = "/bin/nu"
args = []

[colors.primary]
background = "#000005"

[window]
opacity = 0.85
padding = {x = 5, y = 0}
dynamic_padding = true

[font]
normal.family = "MesloLGM Nerd Font"
size = 13
