[terminal.shell]
program = "/bin/nu"
args = []

[colors.primary]
background = "#000005"

[window]
opacity = 0.88
dynamic_padding = true

[font]
normal.family = "MesloLGM Nerd Font"
size = 13

[mouse]
hide_when_typing = true
